version: '3'

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - WEBUI_USERNAME=test
      - WEBUI_PASSWORD=test
    volumes:
      - /path/to/appdata/config:/config
      - movie_data:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  movie_server:
    image: nginx:alpine
    container_name: movie_server
    volumes:
      - movie_data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80

volumes:
  movie_data:
